// Search index data for this page — consumed by docs-common.js
const searchIndex = [
      { title: "Introduction to AI & ML", desc: "What AI and ML are, and how they relate", id: "intro" },
      { title: "Types of Machine Learning", desc: "Supervised, unsupervised, reinforcement", id: "ml-types" },
      { title: "Math Foundations", desc: "Linear algebra, calculus, probability", id: "math-foundations" },
      { title: "Environment Setup", desc: "venv, conda, TensorFlow, PyTorch, Jupyter", id: "setup" },
      { title: "NumPy Fundamentals", desc: "Arrays, broadcasting, vectorized ops", id: "numpy" },
      { title: "Pandas for Data Manipulation", desc: "DataFrames, cleaning, grouping, merging", id: "pandas" },
      { title: "Data Visualization", desc: "Matplotlib, Seaborn, distributions, heatmaps", id: "visualization" },
      { title: "Data Preprocessing", desc: "Scaling, encoding, feature engineering", id: "preprocessing" },
      { title: "Scikit-learn Basics", desc: "Pipelines, fit/predict API", id: "sklearn" },
      { title: "Regression Algorithms", desc: "Linear, Ridge, Lasso, tree-based regressors", id: "regression" },
      { title: "Classification Algorithms", desc: "Logistic regression, SVM, trees, boosting", id: "classification" },
      { title: "Clustering & Dim. Reduction", desc: "K-Means, DBSCAN, PCA, t-SNE", id: "clustering" },
      { title: "Ensemble Methods", desc: "Bagging, boosting, stacking, XGBoost", id: "ensemble" },
      { title: "Evaluation Metrics", desc: "Accuracy, precision, recall, F1, ROC-AUC", id: "metrics" },
      { title: "Overfitting & Regularization", desc: "L1/L2, dropout, early stopping", id: "regularization" },
      { title: "Cross-Validation & Tuning", desc: "K-Fold, GridSearchCV, Optuna", id: "tuning" },
      { title: "Neural Network Fundamentals", desc: "Neurons, activations, backpropagation", id: "neural-networks" },
      { title: "TensorFlow & Keras", desc: "Sequential models, compile, fit", id: "tensorflow" },
      { title: "PyTorch", desc: "nn.Module, autograd, training loops", id: "pytorch" },
      { title: "Convolutional Networks", desc: "CNNs for computer vision", id: "cnn" },
      { title: "Recurrent Networks & Sequences", desc: "RNN, LSTM, GRU, Seq2Seq", id: "rnn" },
      { title: "Transformers & Attention", desc: "Self-attention, BERT, GPT architecture", id: "transformers" },
      { title: "Natural Language Processing", desc: "Embeddings, NER, sentiment analysis", id: "nlp" },
      { title: "Computer Vision", desc: "Detection, segmentation, image generation", id: "computer-vision" },
      { title: "Generative AI & LLMs", desc: "LLMs, diffusion models, RAG, RLHF", id: "generative-ai" },
      { title: "Transfer Learning", desc: "Pretrained models, fine-tuning", id: "transfer-learning" },
      { title: "Reinforcement Learning", desc: "Agents, rewards, Q-learning, PPO", id: "reinforcement-learning" },
      { title: "Model Deployment & MLOps", desc: "Serving, versioning, monitoring", id: "deployment" },
      { title: "Ethics & Responsible AI", desc: "Bias, fairness, privacy, explainability", id: "ethics" }
    ];
