// Search index data for this page — consumed by docs-common.js
const searchIndex = [
      { title: "Introduction to Linux", desc: "What Linux is and why it matters", id: "intro" },
      { title: "Linux Distributions", desc: "Debian, Red Hat, Arch, SUSE and more", id: "distributions" },
      { title: "Terminal Basics", desc: "Shells, history, keyboard shortcuts", id: "terminal" },
      { title: "File System Hierarchy", desc: "The FHS directory structure", id: "filesystem" },
      { title: "Navigation Commands", desc: "pwd, cd, ls, tree, file", id: "navigation" },
      { title: "File Operations", desc: "touch, cp, mv, rm, mkdir, ln", id: "file-ops" },
      { title: "File Permissions", desc: "chmod, umask, rwx notation", id: "permissions" },
      { title: "Ownership & ACL", desc: "chown, chgrp, setfacl, getfacl", id: "ownership" },
      { title: "Archiving & Compression", desc: "tar, gzip, bzip2, xz, zip", id: "archiving" },
      { title: "grep & Regular Expressions", desc: "Pattern matching in text", id: "grep" },
      { title: "sed Stream Editor", desc: "Non-interactive text substitution", id: "sed" },
      { title: "awk Programming", desc: "Column-based text processing", id: "awk" },
      { title: "Pipes & Redirection", desc: "stdin, stdout, stderr, tee", id: "pipes" },
      { title: "Users & Groups", desc: "useradd, usermod, groups", id: "users" },
      { title: "sudo & Privileges", desc: "Privilege escalation, sudoers", id: "sudo" },
      { title: "SSH & Remote Access", desc: "Secure shell, scp, rsync, keys", id: "ssh" },
      { title: "Processes & Jobs", desc: "ps, top, htop, job control", id: "processes" },
      { title: "Signals & Kill", desc: "SIGTERM, SIGKILL, kill, pkill", id: "signals" },
      { title: "Cron & Scheduling", desc: "crontab and systemd timers", id: "cron" },
      { title: "Network Commands", desc: "ip, ping, curl, wget, ss", id: "net-commands" },
      { title: "Firewall & iptables", desc: "ufw, firewalld, netfilter rules", id: "firewall" },
      { title: "DNS & Hostname", desc: "dig, nslookup, /etc/hosts", id: "dns" },
      { title: "APT (Debian/Ubuntu)", desc: "apt, dpkg package management", id: "apt" },
      { title: "DNF/YUM (RHEL/Fedora)", desc: "dnf, rpm package management", id: "dnf" },
      { title: "Pacman (Arch)", desc: "Arch Linux package management", id: "pacman" },
      { title: "Snap, Flatpak & AppImage", desc: "Distro-agnostic packaging", id: "universal" },
      { title: "systemd & Services", desc: "systemctl, unit files", id: "systemd" },
      { title: "journalctl & Logs", desc: "Reading the systemd journal", id: "journalctl" },
      { title: "Kernel Modules", desc: "lsmod, modprobe, insmod", id: "kernel" },
      { title: "Disk & Storage", desc: "df, du, lsblk, mount, LVM", id: "disk" },
      { title: "Bash Basics", desc: "Writing your first shell scripts", id: "bash-basics" },
      { title: "Variables & Expansion", desc: "Shell variables, arrays, arithmetic", id: "variables" },
      { title: "Conditionals & Loops", desc: "if, for, while, case", id: "conditionals" },
      { title: "Functions", desc: "Reusable bash functions", id: "functions" },
      { title: "Security Basics", desc: "Hardening a Linux system", id: "security-basics" },
      { title: "SELinux & AppArmor", desc: "Mandatory access control", id: "selinux" },
      { title: "Encryption & Keys", desc: "LUKS, GPG, checksums, TLS", id: "encryption" },
      { title: "Containers & Docker", desc: "Docker, Dockerfile, Compose", id: "containers" },
      { title: "Virtualization", desc: "KVM, QEMU, libvirt", id: "virtualization" },
      { title: "Performance Tuning", desc: "vmstat, iostat, strace, lsof", id: "performance" }
    ];
