// Search index data for this page — consumed by docs-common.js
const searchIndex = [
      { title: "Introduction to Network Security", desc: "CIA triad, security domains, and fundamentals", id: "intro" },
      { title: "OSI Model", desc: "Seven-layer reference model for network communication", id: "osi-model" },
      { title: "TCP/IP Stack", desc: "The practical four-layer internet protocol suite", id: "tcp-ip" },
      { title: "Network Protocols", desc: "ARP, DNS, ICMP and their security implications", id: "protocols" },
      { title: "Firewall Concepts", desc: "Types of firewalls and traffic filtering", id: "firewall-concepts" },
      { title: "iptables", desc: "Classic Linux netfilter firewall", id: "iptables" },
      { title: "nftables", desc: "Modern replacement for iptables", id: "nftables" },
      { title: "firewalld", desc: "Dynamic firewall for RHEL systems", id: "firewalld" },
      { title: "UFW", desc: "Uncomplicated Firewall for Ubuntu/Debian", id: "ufw" },
      { title: "Penetration Testing Basics", desc: "Types, methodology, and legal considerations", id: "pentest-intro" },
      { title: "Reconnaissance", desc: "Passive and active information gathering", id: "reconnaissance" },
      { title: "Scanning & Enumeration", desc: "Nmap, service discovery, and enumeration", id: "scanning" },
      { title: "Exploitation", desc: "Vulnerability exploitation with Metasploit", id: "exploitation" },
      { title: "Post-Exploitation", desc: "Privilege escalation, lateral movement, persistence", id: "post-exploitation" },
      { title: "Wireless Standards", desc: "IEEE 802.11 family and wireless modes", id: "wireless-standards" },
      { title: "WEP & WPA", desc: "Wireless encryption evolution and attacks", id: "wep-wpa" },
      { title: "Wireless Attacks", desc: "Evil twin, deauth, WPS, and PMKID attacks", id: "wireless-attacks" },
      { title: "Wireless Defense", desc: "Securing Wi-Fi networks against attacks", id: "wireless-defense" },
      { title: "IDS/IPS Concepts", desc: "Intrusion detection and prevention fundamentals", id: "ids-ips-concepts" },
      { title: "Snort", desc: "Open-source IDS/IPS with rule-based detection", id: "snort" },
      { title: "Suricata", desc: "High-performance multi-threaded IDS/IPS", id: "suricata" },
      { title: "Zeek", desc: "Network analysis framework for security monitoring", id: "zeek" },
      { title: "SIEM & Log Analysis", desc: "Centralized security monitoring and threat detection", id: "siem" },
      { title: "VPN Types", desc: "Remote access, site-to-site, and mesh VPNs", id: "vpn-types" },
      { title: "OpenVPN", desc: "SSL/TLS VPN setup and configuration", id: "openvpn" },
      { title: "WireGuard", desc: "Modern fast and simple VPN protocol", id: "wireguard" },
      { title: "IPsec", desc: "Standard protocol suite for secure IP communications", id: "ipsec" },
      { title: "TLS/SSL", desc: "Transport Layer Security and certificate management", id: "tls-ssl" },
      { title: "Nmap", desc: "Network discovery and security auditing", id: "nmap" },
      { title: "Metasploit", desc: "Penetration testing framework", id: "metasploit" },
      { title: "Burp Suite", desc: "Web application security testing platform", id: "burp-suite" },
      { title: "Wireshark", desc: "Network protocol analyzer", id: "wireshark" },
      { title: "Hashcat & John", desc: "Password recovery and hash cracking", id: "hashcat" },
      { title: "OWASP Top 10", desc: "Critical web application security risks", id: "owasp-top10" },
      { title: "XSS", desc: "Cross-site scripting attacks and prevention", id: "xss" },
      { title: "SQL Injection", desc: "Database query manipulation and defense", id: "sql-injection" },
      { title: "CSRF", desc: "Cross-site request forgery and protection", id: "csrf" },
      { title: "Web Defense", desc: "Security headers, WAF, and best practices", id: "web-defense" },
      { title: "Network Segmentation", desc: "VLANs, zones, and isolation strategies", id: "network-segmentation" },
      { title: "Bastion Host", desc: "Hardened gateway for secure admin access", id: "bastion-host" },
      { title: "Zero Trust", desc: "Never trust, always verify architecture", id: "zero-trust" },
      { title: "Hardening", desc: "System hardening and security benchmarks", id: "hardening" }
    ];
