// Search index data for this page — consumed by docs-common.js
const searchIndex = [
      { title: "Introduction to Python", desc: "Python What is it and why should you or", id: "intro" },
      { title: "Installation and Setup", desc: "Python and creating virtual environment", id: "install" },
      { title: "Basic Syntax", desc: "Basic rules for writing Python code", id: "syntax" },
      { title: "Variables and Data Types", desc: "Storing and managing data‌", id: "variables" },
      { title: "Operators", desc: "OperatorsPython", id: "operators" },
      { title: "Conditional if-else", desc: "orWith condition‌", id: "if-else" },
      { title: "Loops", desc: "for while", id: "loops" },
      { title: "Comprehension", desc: "Data Structures ", id: "comprehensions" },
      { title: "Match-Case", desc: "Pattern Matching in Python 3.10+", id: "match-case" },
      { title: "Lists", desc: "Sequential and mutable data structure", id: "lists" },
      { title: "Tuples", desc: "Data Immutable", id: "tuples" },
      { title: "Dictionaries", desc: "Key-value data structure", id: "dicts" },
      { title: "Sets", desc: "Data structure with unique members", id: "sets" },
      { title: "Strings", desc: "Working with text in Python", id: "strings" },
      { title: "Functions", desc: "Definition and use of Functions", id: "functions" },
      { title: "Lambda", desc: "Anonymous one-line functions", id: "lambda" },
      { title: "Decorators", desc: "Functions", id: "decorators" },
      { title: "Modules and Packages", desc: "Organization", id: "modules" },
      { title: "Generators", desc: "Generating values lazily", id: "generators" },
      { title: "Classes and Objects", desc: "With OOP", id: "classes" },
      { title: "Inheritance", desc: "‌Class‌", id: "inheritance" },
      { title: "Encapsulation", desc: "‌Data‌", id: "encapsulation" },
      { title: "Polymorphism", desc: "One interface, different implementations", id: "polymorphism" },
      { title: "Magic Methods", desc: "Methoddunder", id: "magic-methods" },
      { title: "Read and write File", desc: "File Handling", id: "file-io" },
      { title: "Context Manager", desc: "Managing resources with with", id: "context-managers" },
      { title: "CSV and JSON", desc: "Format‌Data", id: "csv-json" },
      { title: "Try-Except", desc: "Error Handling", id: "try-except" },
      { title: "Custom Exceptions", desc: "Creating your own exceptions", id: "custom-exceptions" },
      { title: "Finally and Else", desc: "Complementary parts of try-except", id: "finally-else" },
      { title: "Iterators", desc: "And iteration", id: "iterators" },
      { title: "Contextlib", desc: "Context Manager tools", id: "contextlib" },
      { title: "Metaclasses", desc: "Classes that create classes", id: "metaclasses" },
      { title: "Async/Await", desc: "Name‌Asynchronous", id: "async" },
      { title: "Type Hints", desc: "Python type system", id: "typing" },
      { title: "os and sys", desc: "Interacting with the operating system", id: "os-sys" },
      { title: "datetime", desc: "Working with dates and times", id: "datetime" },
      { title: "Regular Expressions", desc: "Pattern matching regex", id: "re" },
      { title: "Collections", desc: "Specialized data structures", id: "collections" },
      { title: "Itertools", desc: "Iterator tools", id: "itertools" },
      { title: "unittest", desc: "Test", id: "unittest" },
      { title: "pytest", desc: "‌Test", id: "pytest" },
      { title: "Debugging Techniques", desc: "And Debugging Techniques", id: "debugging" },
      { title: "Performance Tips", desc: "Optimizing Python code", id: "performance" },
      { title: "Profiling", desc: "Analyzing code performance", id: "profiling" },
      { title: "Memory Management", desc: "Understanding and optimizing memory usage", id: "memory" }
    ];
